server:
  port: 8080
#logging:
#  file: spring.log
#  path: /spring/log     #在当前文件下创建
#  pattern:
#    file: "%d - %msg%n"
#    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} -%5p ${PID:-} [%15.15t] %-30.30C{1.} : %m%n"
#spring:     #指定激活环境
#  profiles:
#    active: dev
spring:
  thymeleaf:
    cache: false # 开发时关闭缓存,不然没法看到实时页面
    mode: LEGACYHTML5 # 用非严格的 HTML
    encoding: UTF-8
    servlet:
      content-type: text/html
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
    virtualHost: /
  datasource:
    druid:
      url: jdbc:mysql://localhost:3306/xc_course?characterEncoding=utf-8
      username: root
      password: mysql
      driverClassName: com.mysql.jdbc.Driver
      initialSize: 5  #初始建立连接数量
      minIdle: 5  #最小连接数量
      maxActive: 20 #最大连接数量
      maxWait: 10000  #获取连接最大等待时间，毫秒
      testOnBorrow: true #申请连接时检测连接是否有效
      testOnReturn: false #归还连接时检测连接是否有效
      timeBetweenEvictionRunsMillis: 60000 #配置间隔检测连接是否有效的时间（单位是毫秒）
      minEvictableIdleTimeMillis: 300000  #连接在连接池的最小生存时间（毫秒）
  data:         #mongo配置
    mongodb:
      database: xc_fs
      uri: mongodb://root:123@127.0.0.1:27017
  servlet:      #SpringMVC上传文件配置
    multipart:
      enabled: true         #默认支持文件上传.
      file-size-threshold: 0         #支持文件写入磁盘.
      location:               # 上传文件的临时目录
      max-file-size: 1MB            # 最大支持文件大小
      max-request-size: 30MB             # 最大支持请求大小
  redis:
    database: 0      # Redis数据库索引（默认为0）
    host: 47.98.136.216  # Redis服务器地址
    port: 6379       # Redis服务器连接端口
    password:        # Redis服务器连接密码（默认为空）
    jedis:
      pool:
        maxActive: 3
        maxIdle: 3
        minIdle: 1








